# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
    # Schedule updates (every week)
    schedule: [{ cron: "0 0 * * 0" }]
    # Lines below let you run workflow manually and on each commit
    workflow_dispatch:
    workflow_call:
jobs:
    github-metrics:
        runs-on: ubuntu-latest
        steps:
            - uses: lowlighter/metrics@latest
              with:
                  token: ${{ secrets.METRICS_TOKEN }}
                  user: Bogstag
                  committer_branch: stats
                  committer_message: "[Auto] new metrics generated"
                  filename: images/github-metrics.svg
                  output_action: commit
                  optimize: svg
                  template: classic
                  config_display: large
                  config_output: svg
                  retries: 1
                  config_timezone: Europe/Stockholm

                  base: header, activity, community, repositories, metadata
                  base_indepth: yes
                  repositories: 200
                  repositories_forks: yes
                  repositories_affiliations: owner, collaborator, organization_member
                  # commits_authoring:

                  plugin_achievements: yes
                  plugin_achievements_display: detailed
                  plugin_achievements_secrets: yes
                  plugin_achievements_threshold: C

                  plugin_habits_charts: no
                  plugin_habits_days: 28
                  plugin_habits_facts: yes
                  plugin_habits_from: 500
                  plugin_habits_languages_limit: 8
                  plugin_habits_trim: yes
                  plugin_habits: yes

                  plugin_languages: yes
                  plugin_languages_analysis_timeout: 30
                  plugin_languages_categories: markup, programming, data, prose
                  plugin_languages_details: percentage
                  plugin_languages_limit: 10

                  plugin_lines: yes
                  plugin_lines_sections: base, repositories, history
                  plugin_lines_delay: 60

                  plugin_starlists: no

                  plugin_topics_mode: icons
                  plugin_topics: yes

                  plugin_traffic: yes

                  plugin_projects: no

                  plugin_licenses: yes
                  plugin_licenses_ratio: yes

                  plugin_calendar: yes
                  plugin_calendar_limit: 0
