name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          #  - repo
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.GITHUBPROFILE }}

          # Options
          user: Bogstag
          template: classic
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          config_timezone: Europe/Stockholm
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_achievements: yes
          plugin_gists: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 2%
          plugin_habits_trim: yes
          plugin_habits: yes
          plugin_languages_analysis_timeout_repositories: .
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming, data, prose
          plugin_languages_colors: github
          plugin_languages_details: percentage
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming, data, prose
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_languages: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          plugin_lines: yes
          plugin_notable_from: all
          plugin_notable_types: commit, pull_request, issue
          plugin_notable_filter: stars, forks, watchers
          plugin_notable_repositories: yes
          plugin_notable: yes
          plugin_repositories_starred: 2
          plugin_stars_limit: 2
          plugin_stars: yes
          plugin_traffic: yes
