name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUBPROFILE }}
          user: Bogstag
          template: classic
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          config_timezone: Europe/Stockholm
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_gists: yes
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 
          plugin_habits_facts: yes
          plugin_habits_from: 
          plugin_habits_languages_limit: 
          plugin_habits_languages_threshold: %
          plugin_languages: yes
          plugin_languages_analysis_timeout: 
          plugin_languages_analysis_timeout_repositories: .
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 
          plugin_languages_recent_load: 
          plugin_languages_sections: most-used
          plugin_languages_threshold: %
          plugin_lines: yes
          plugin_lines_history_limit: 
          plugin_lines_repositories_limit: 
          plugin_lines_sections: base
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_types: commit
