name: Metrics
on:
    # Schedule daily updates
    schedule: [{ cron: "0 0 * * *" }]
    # (optional) Run workflow manually
    workflow_dispatch:
jobs:
    github-metrics:
        runs-on: ubuntu-latest
        environment:
            name: production
        permissions:
            contents: write
        steps:
            - uses: lowlighter/metrics@latest
              with:
                  filename: github-metrics.svg
                  token: ${{ secrets.METRIC_TOKEN }}
                  user: Bogstag
                  template: classic

                  config_timezone: Europe/Stockholm
                  config_output: svg

                  base: header, activity, community, repositories, metadata
                  base_indepth: yes
                  repositories: 200
                  repositories_batch: 70
                  repositories_affiliations: owner, collaborator, organization_member

                  plugin_achievements_ignored: manager
                  plugin_achievements: yes

                  plugin_gists: yes

                  plugin_habits_languages_limit: 12
                  plugin_habits_trim: yes
                  plugin_habits_charts_type: graph
                  plugin_habits_days: 28
                  plugin_habits_from: 400
                  plugin_habits: yes

                  plugin_languages_analysis_timeout_repositories: 15
                  plugin_languages_analysis_timeout: 30
                  plugin_languages_categories: markup, programming, data, prose
                  plugin_languages_details: percentage
                  plugin_languages_limit: 12
                  plugin_languages: yes

                  plugin_lines: yes

                  plugin_notable_types: commit, pull_request, issue
                  plugin_notable_repositories: yes
                  plugin_notable_from: all
                  plugin_notable_filter: stars, forks, watchers
                  plugin_notable: yes

                  plugin_starlists: yes
                  plugin_starlists_languages: yes

                  plugin_traffic: yes
